### ISSUE TITLE
Change DNS entries for ssb.freeside.network and subdomains

### ISSUE THREAD

**Issue by boreq** [freeside-network/freeside.network#7]
Please point `ssb.freeside.network` as well as all subdomains `*.ssb.freeside.network` to the same IP address as `0x46.net`.

I imagine this can be done with some kind of an alias instead of hard-coding the IP, however if that is impossible then let it be known that this IP doesn't really change.

**Comment by boreq** [comment]
@lovelaced

**Comment by lovelaced** [comment]
These records have been added. can you please verify it's working as expected?

**Comment by boreq** [comment]
I think it works.
